 #########################Version: @version@
 #  ▄▄  ▄ ▄  ▄  ▄▄  ▄▄▄ ▄▄▄ ▄▄▄▄   ˏ—ˎ    #
 #  █▄█ █▄█ █▄█ █ █  █  █ █ █ █ █ (oˍo\   #
 #  █   █ █ █ █ █ █  █  █▄█ █   █ ʿ\˷̰ʿ˷ܥ̀  #
 #  Minecraft Server Broadcasting System  #
 #  —————————— [ CORE SERVER ]——————————  #
 # discord.gg/ASgcxVvhU9 | phantomhost.cc #
 ##########################################
